//throwaway acc can be uploaded to gh

static GLOBAL_ACC: &str = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiVEhST1dfMTk0OTMiLCJ2ZXJzaW9uIjoidjIiLCJyZXNldF9kYXRlIjoiMjAyMy0wNS0yMCIsImlhdCI6MTY4NDY0NzgzOCwic3ViIjoiYWdlbnQtdG9rZW4ifQ.qh6qkeS5-_IM3Hzf9HY5axEXohFMPLCBqXwIkiviQtjMOVW1dTfzo2s9TFD96dy3XBovj3ZsN7DiKcZZ9fcRHtBZaW-Z7IBLl79gyvHRyqEGLZPPYohhCEyC_5oXstSAadQvu1_a4u8ZV1AoljAOr3uWXHuMlF1qTnnC0Pccj7qQ_S0raYt0zzL_rTXwutiU9sWBesYkGudaVzWmaEqniL54LMtLDG9YUETgYgEbCuvHrQIlib7gPvFq5Jd6LHewGFN97Gxzjig7L9uYWPkIIkEMMJcG0Lm5J4Ljlte_ykjHcA4h4bFW3po9wyz3mIVk5YVuqgqhJFqAkJ8PjAxIRw";

mod agents_api;
mod default_api;
mod factions_api;
mod contracts_api;
mod fleet_api;
mod systems_api;
